# This Python file uses the following encoding: utf-8
from django.core.exceptions import ObjectDoesNotExist
from debra.models import Items, CategoryModel, ProductModel, ColorSizeModel
from debra.models import Brands, StoreSpecificItemCategory
from django.utils.encoding import smart_unicode

PROD_MODEL_BASED = 0
SHOPSTYLE_BASED = 1
NAME_BASED = 2

static_categories = {'Express': ['1MX Shirts', 'Shirts', 'Polos', 'Graphic Tees', 'Tees', 
                                 'Hoodies & Jackets', 'Jeans', 'Shorts & Swim', 'Suits & Jackets',
                                 'Pants', 'Sweaters', 'Outerwear', 'Ties', 'Shoes', 'Watches', 
                                 'Accessories & Belts', 'Underwear', 'Socks', 'Fragrance & Grooming', 
                                 'Slim Fit Shop', 'Must-Have Looks', 'Sale',
                                 'Dresses', 'Tops & Tees', 'Tanks & Camis', 'Shirts & Blouses', 'Shorts',
                                 'Skirts', 'Suits & Jackets', 'Jackets & Vests', 'Outerwear', 
                                 'Express Sport', 'Intimates & Sleepwear', 'Shoes & Sandals', 
                                 'Accessories', 'Handbags', 'Jewelry', 'Fragrance & Beauty', 'Must-Have Looks',],
                     'Abercrombie & Fitch': ['Tees', 'Polos', 'Shirts', 'Hoodies', 'Sweaters', 'Outerwear',
                                             'Swim', 'Shorts', 'Jeans', 'Sweatpants', 'Pants',
                                             'Flip Flops', 'Accessories', 'Underwear', 'Body Care', 
                                             'Cologne',  
                                             'Tops', 'Hoodies', 'Sweaters', 'Outerwear',
                                             'Skirts', 'Dresses', 'Shorts', 'Pants',
                                             'Jeans', 'Sweatpants', 'Yoga', 'Swim',
                                             'Flip Flops', 'Accessories', 'Bras & Undies',
                                             'Fragrance', 'Sale', 'Clearance', 'Knit Layers', 'Graphic Tees',
                                             'Cardigans', 'Pullovers',
                                             'Denim', 'Lounge', 'The A&F Jegging', 'Super Skinny',
                                             'Midrise Super Skinny', 'Skinny', 'Straight',
                                             'Boot', 'Flare', 'Crop', 'Totes',
                                             'Belts', 'Scarves', 'Plaid', 'Classic', 
                                             'Crew & V-Neck', 'Henley', 
                                             'Classic Shirts', 'Plaid Shirts',
                                             'Flannel Shirts', ],
                     }

static_male_categories = {'Express': ['1MX Shirts', 'Shirts', 'Polos', 'Graphic Tees', 'Tees', 
                                      'Hoodies & Jackets', 'Jeans', 'Shorts & Swim', 'Suits & Jackets',
                                      'Pants', 'Sweaters', 'Outerwear', 'Ties', 'Shoes', 'Watches', 
                                      'Accessories & Belts', 'Underwear', 'Socks', 'Fragrance & Grooming', 
                                      'Slim Fit Shop', 'Must-Have Looks', 'Sale',],
                          'Abercrombie & Fitch': ['Elements of Ivy', 'New Arrivals', 'Flagship Exclusives',
                                                  'Tees', 'Polos', 'Shirts', 'Hoodies', 'Sweaters', 'Outerwear',
                                                  'Swim', 'Shorts', 'Jeans', 'Sweatpants', 'Pants',
                                                  'Flip Flops', 'Accessories', 'Underwear', 'Body Care', 
                                                  'Cologne', 'Sale', 'Clearance', 'A&F Prep', 'Athletic',
                                                  'Graphic Tees', 'Crew & V-Neck', 'Henley',
                                                  'Classic', 'Plaid', 'Classic', 'Button Down',
                                                  'Cardigans', 'Pullovers', 'Classic', 'Super Skinny', 
                                                  'Skinny', 'Slim Straight', 'Classic Straight',
                                                  'Leather', 'Belts', 'Bracelets', 'Boxers', 'Boxer-Briefs',
                                                  'Classic Shirts', 'Plaid Shirts', 'Flannel Shirts',
                                                  ],
                          'Gap': ['New Arrivals', 'Top Story',
                                  'Gap + Threadless Ts', 'Color Khakis & Denim', 'The Slim Fit Shop',
                                  '9-to-5 Styles', 'Customer Favorites', '1969 Denim Guide', 'Outerwear & Blazers',
                                  'Khakis', 'Denim', 'Bottoms',
                                  'Fit & Style','Wash & Care','1969 Stores','Ts & Tanks','Graphic Ts','Polos',
                                  'Shirts','Sweaters','Sweatshirts','Outerwear & Blazers','Jeans',
                                  'Pants','Shorts','Sleep & Lounge','Underwear & Socks','Shoes',
                                  'Accessories', "Piperlime's shoe picks",'Short-Sleeved','Graphics',
                                  'Logo','Long-Sleeved','Tanks','Undershirts','Casual','Non-Iron',
                                  'Dress','Jackets', 'Blazers','Colored Denim','Straight','Skinny','Slouchy Slim', 'Boot',
                                  'Standard','Easy', 'Loose', 'Original', 'Cropped',
                                  'Shorts', 'Denim Washed Khakis', 'Casual', 'Versatile', 'Dress',
                                  'Flat-front & Cargo', 'Denim', 'Lounge', 'Swim', 'Lounge', 'Sleep',
                                  'Boxers', 'Boxer Briefs', 'Briefs', '2-Packs', 'Undershirts',
                                  'Socks', 'Belts', 'Hats', 'Ties', 'Bags', 'Tops', 'Bottoms',
                                  ],
                          
                          'Banana Republic': ['new arrivals','new BR monogram collection','weekend getaway',
                                              'work', 'slim fit shop', 'Mad Men® collection','stock up & save',
                                              'SFMade Collection','dress shirts','non-iron shirts','stretch shirts',
                                              'casual shirts','polos','tees','sweaters','outerwear & jackets',
                                              'blazers','suiting','pants','chinos','jeans','shorts',
                                              'underwear & socks','new special sizes','big & tall','extra small',
                                              'shoes & accessories','shoes',
                                              'bags','belts','ties','pocket squares','hats & scarves',
                                              'cuff links & collar stays','small leather goods','sunglasses',
                                              'giftcards','sale','tops','bottoms','accessories','corporate wear',
                                              'business casual','suits','dress shirts','casual shirts',
                                              'pants & jeans','slim fit','tailored slim','classic fit',
                                              'ties','cuff links','soft-wash','linen shirts','short sleeve',
                                              'pique polos','luxe-touch polos','vintage collection',
                                              'short sleeve tees','graphic tees','essential pima tees',
                                              'long sleeve tees','lightweight layers','pullovers',
                                              'cardigans','lightweight layers','vests','jackets','outerwear',
                                              'lightweight layers','suits','blazers','dress pants',
                                              'casual pants','pants by fit','gavin','dawson',
                                              'boot cut','five-pocket','emerson','straight',
                                              'boot cut','vintage straight','relaxed','boxers',
                                              'socks','essential tees',
                                              'big & tall',
                                              'extra small',
                                              'shoes & accessories',
                                              'shoes',
                                              "Piperlime's shoe picks",
                                              'bags',
                                              'belts',
                                              'ties',
                                              'pocket squares',
                                              'hats & scarves',
                                              'cuff links & collar stays',
                                              'small leather goods',
                                              'sunglasses',
                                              'sale',
                                              'shops',
                                              'new arrivals',
                                              'new BR monogram collection',
                                              'weekend getaway',
                                              'work',
                                              'the slim fit shop',
                                              'Mad Men® collection',
                                              'apparel',
                                              'dress shirts',
                                              'non-iron shirts',
                                              'stretch shirts',
                                              'casual shirts',
                                              'polos',
                                              'tees',
                                              'sweaters',
                                              'outerwear & jackets',
                                              'blazers',
                                              'suiting',
                                              'pants',
                                              'chinos',
                                              'jeans',
                                              'shorts',
                                              'underwear & socks',
                                              'shoes & accessories',
                                              'shoes',
                                              'bags',
                                              'belts',
                                              'ties',
                                              'hats & scarves',
                                              'cuff links & collar stays',
                                              'small leather goods',
                                              "men's sunglasses",
                                              'giftcards',
                                              'sale',
                                              'suits',
                                              'dress shirts',
                                              'casual shirts',
                                              'pants & jeans',
                                              'slim fit',
                                              'tailored slim',
                                              'classic fit',
                                              'ties',
                                              'cuff links',                                  
                                              'soft-wash',
                                              'linen shirts',
                                              'short sleeve', 'pique polos', 'luxe-touch polos', 'vintage collection',
                                              'short sleeve tees', 'graphic tees', 'essential pima tees', 'fitted tees',
                                              'long sleeve', 'lightweight layers', 'pullovers', 'cardigans',
                                              'vests', 'jackets', 'outerwear', 'lightweight layers',
                                              'suits', 'blazers', 'dress pants', 'casual pants',
                                              'pants by fit', 'gavin', 'dawson', 'boot cut',
                                              'five-pocket', 'emerson', 'vintage straight', 'straight', 'boot cut',
                                              'vintage straight', 'relaxed', 'boxers', 'socks', 'essential tees',
                                              'loafers', 'oxfords', 'sneakers', 'jackets', 'polos & tees',
                                              'shirts', 'sweaters', 'pants', 'suits & blazers', 'shoes', 'accessories',
                                              ]
                          }


static_female_categories = {'Express': ['Dresses', 'Tops & Tees', 'Tanks & Camis', 'Shirts & Blouses', 'Sweaters',
                                        'Jeans', 'Pants', 'Shorts', 'Skirts', 'Suits & Jackets', 'Jackets & Vests', 'Outerwear', 
                                        'Express Sport', 'Intimates & Sleepwear', 'Shoes & Sandals', 
                                        'Accessories', 'Handbags', 'Jewelry', 'Fragrance & Beauty', 'Must-Have Looks', 'Sale'],
                            'Abercrombie & Fitch': ['Elements of Ivy', 'New Arrivals', 'Flagship Exclusives', 'A&F Classic Pretty',
                                                    'Tops', 'Hoodies', 'Sweaters', 'Outerwear',
                                                    'Skirts', 'Dresses', 'Shorts', 'Pants',
                                                    'Jeans', 'Sweatpants', 'Yoga', 'Swim',
                                                    'Flip Flops', 'Accessories', 'Bras & Undies',
                                                    'Fragrance', 'Sale', 'Clearance', 'Knit Layers', 'Graphic Tees',
                                                    'Polos', 'Shirts', 'Fashion', 'Tanks', 'Short Sleeve', 'Long Sleeve', 
                                                    'Classic', 'Plaid', 'Button Down',
                                                    'Cardigans', 'Pullovers',
                                                    'Denim', 'Lounge', 'The A&F Jegging', 'Super Skinny',
                                                    'Midrise Super Skinny', 'Skinny', 'Straight',
                                                    'Banded', 'Lounge', 'Push Up', 'Triangle', 'Bandeau',
                                                    'Bottoms', 'Leather', 'Totes', 'Belts', 'Scarves',
                                                    'Boot', 'Flare', 'Crop',   'Plaid', 'Classic'],
                            'Gap': [
                                  'New Arrivals',
                                  'Gap + Threadless Ts',
                                  'Summer Destinations',
                                  'Styld.by',
                                  'Pretty Printed Dresses',
                                  'The Accessories Shop',
                                  'Style at Work',
                                  'Gap Pure',
                                  'Trends We Love',
                                  'Customer Favorites',
                                  '1969 Denim Guide',
                                  'Tops',
                                  'Bottoms',
                                  'Dresses',
                                  'Outerwear & Blazers',
                                  'GapFit',
                                  'Sleepwear',
                                  'Lounge',
                                  'Pure Body',
                                  'Swim',
                                  'Shoes',
                                  'Accessories',
                                  'Summer Whites',
                                  'Color Denim',
                                  'Beachy Sweaters',
                                  'Sherbet Shades',
                                  'Vintage-Wash Denim',
                                  'New & Now',
                                  'Fit & Style',
                                  'Fabric Notes',
                                  '1969 Fit Facts',
                                  'Wash & Care',
                                  '1969 Stores',
                                  'Short-Sleeved',
                                  'Long-Sleeved',
                                  'Tanks & Camis',
                                  'Favorite',
                                  'Hoodies & More',
                                  'Pure Body',
                                  'Sleeveless',
                                  'Crewnecks & V-Necks',
                                  'Cardigans & Wraps',
                                  'Vests',
                                  'Dresses',
                                  'Skirts',
                                  'Colored Denim',
                                  'Legging Jean',
                                  'Always Skinny',
                                  'Sexy Boot',
                                  'Trouser & Flare',
                                  'Perfect Boot',
                                  'Sexy Boyfriend',
                                  'Curvy',
                                  'Real Straight',
                                  'Long & Lean',
                                  'Original Fit',
                                  'Jackets',
                                  'Blazers & Vests',
                                  'Leather & Suede',
                                  'Scarves',
                                  'Handbags',
                                  'Belts',
                                  'Umbrellas',
                                  'Socks',
                                  'Tights & Leggings',
                                  'Wedges & Heels',
                                  'Flats & Ballets',
                                  'Sandals',
                                  'Flip Flops',
                                  'Boots',
                                  'Ts & Tops',
                                  'Shirts & Blouses',
                                  'Logo',
                                  'Hoodies & Sweaters',
                                  'Sweaters',
                                  'Dresses & Skirts',
                                  'Shorts',
                                  'Premium Pants',
                                  'Khakis by Gap',
                                  'Casual Pants',
                                  'Jeans',
                                  'Outerwear & Blazers',
                                  'Accessories',
                                  'Shoes',                             
                                  "Piperlime's shoe picks",
                                  'GapFit',
                                  'Performance',
                                  'Lifestyle',
                                  'Pants & Shorts',
                                  'Tops',
                                  'Hoodies & Jackets',
                                  'Sport',
                                  'Maternity',
                                  'Bras',
                                  'Shop by Collection',
                                  'Made to Match',
                                  'Lovely in Lace',
                                  'Everyday Essentials',
                                  'Shop by Fit',
                                  'T-Shirt',
                                  'Plunge',
                                  'Push-Up',
                                  'Strapless',
                                  'Wireless',
                                  'Demi',                              
                                  'Sport',
                                  'Nursing',
                                  'Panties',
                                  'Candy Store',
                                  'Lovely in Lace',
                                  'Cotton Classics',
                                  'Bikini',
                                  'Thong',
                                  'Tanga',
                                  'Hipster',
                                  'Girl Short',
                                  'High Cut',
                                  'Sleepwear',
                                  'Tops',
                                  'Bottoms',
                                  'Gowns & Rompers',
                                  'Sleep Sets',
                                  'Robes',
                                  'Gowns',
                                  'Swim',
                                  'Fashion Separates',
                                  'Essential Separates',
                                  'One-Pieces',
                                  'Sale',
                                  'Pants',
                                  'Jeans',
                                  'Capris & Shorts',
                                  'Sweaters',
                                  'Ts & Tops',
                                  'Shirts & Blouses',
                                  'Dresses & Skirts',
                                  'Outerwear',
                                  'Lounge & GapBodyFit',
                                  'Sleepwear',                                                             
                                  'Shoes',
                                  'Accessories',
                                  'Swim Collection',
                                  'Meet GapBody Love',
                                  'We Love Lingerie',
                                  'Customer Favorites',
                                  'Gowns & Rompers',
                                  'GapFit',
                                  'Performance',
                                  'Lifestyle',
                                  'Pants & Shorts',
                                  'Tops',
                                  'Hoodies & Jackets',
                                  'Maternity',
                                  'Sports Bras',
                                  'Sleep Sets',
                                  'Robes',
                                  'Slips & Shapewear',
                                  'Ts & Camis',
                                  'Shirts',
                                  'Sweaters',
                                  'Dresses & Skirts',
                                  'Jeans',
                                  'Pants',
                                  'Shorts & Capris',
                                  'GapFit',
                                  'Swim',
                                  'Sleepwear',
                                  'Nursing',
                                  'Bras & Panties',
                                  'Fit & Style Guide',
                                  'New Arrivals',
                                  'Color Bottoms',
                                  'Starter Wardrobe',
                                  'Pure Body',
                                  'Online-Only Styles',
                                  'Work Essentials',
                                  'Customer Favorites',
                                  "Baby's First Favorites",
                                  'New Looks',
                                  'See All Styles',
                                  'Underwear',
                                  'Short-Sleeved Ts',
                                  'Long-Sleeved Ts',
                                  'Tanks & Camis',
                                  'Nursing Tops',
                                  'Demi Panel',
                                  'Full Panel',
                                  'Nursing Bras',
                                  'Nursing Tops',
                                  'Under Belly Panties',
                                  'Bikini & Thong',
                                  ],
                            "Banana Republic": [
                                                'boutiques',
                                                'new arrivals',
                                                'Mad Men® collection',
                                                'stylish work',
                                                'outfits we love',
                                                'SFMade Collection',
                                                'apparel',
                                                'tops',
                                                'layering tees',
                                                'blouses & shirts',
                                                'sweaters',
                                                'dresses',
                                                'skirts',
                                                'pants by fit',
                                                'pants',
                                                'crops & shorts',
                                                'denim',
                                                'suit collections',
                                                'outerwear & blazers',
                                                'collections',
                                                'heritage collection',
                                                'BR monogram collection',
                                                'shoes & accessories',
                                                'shoes',
                                                'handbags',
                                                'sunglasses',
                                                'jewelry',
                                                'accessories',
                                                'safari style',
                                                'citrus hues',
                                                'strong accents',
                                                'bags that work',
                                                'relaxed & refined',
                                                'desk to date',
                                                'sleeveless',
                                                'short sleeve',
                                                'long sleeve',
                                                'sleeveless',
                                                'short sleeve',
                                                'long sleeve',
                                                'long sleeve',
                                                'short sleeve',
                                                'sleeveless',
                                                'classic button down',
                                                'fashion sweaters',
                                                'crew & v-necks',
                                                'cardigans',
                                                'cowl & turtlenecks',
                                                'turtlenecks',
                                                'layering pieces',
                                                'dresses & skirts',
                                                'dresses',
                                                'skirts',
                                                'scarves',
                                                'day to night',
                                                'casual chic',
                                                'special occasion',
                                                'little black dresses',
                                                'shoes',
                                                'belts',
                                                'pencil',
                                                'a-line/full',
                                                'martin',
                                                'jackson',
                                                'logan',
                                                'sloan',
                                                'trouser',
                                                'wide leg',
                                                'flare',
                                                'straight',
                                                'leggings & skinny',
                                                'flare & wide leg',
                                                'trouser',
                                                'boot-cut',
                                                'belts',
                                                'sleek suiting',
                                                'lightweight wool',
                                                'outerwear',
                                                'blazers',
                                                'sandals',
                                                'flats',
                                                'pumps & heels',
                                                'boots',
                                                'totes & hobos',
                                                'small bags & clutches',
                                                'bracelets',
                                                'necklaces',
                                                'earrings',
                                                'rings',
                                                'hair accessories',
                                                'brooches',
                                                'scarves & wraps',
                                                'hats',
                                                'belts',
                                                'tights',
                                                'socks',
                                                'tops',
                                                'layering tees',
                                                'blouses & shirts',
                                                'sweaters',
                                                'dresses & skirts',
                                                'pants by fit',
                                                'pants',
                                                'denim',
                                                'suit collections',
                                                'outerwear & blazers',
                                                'shoes',
                                                'handbags',
                                                'sunglasses',
                                                'jewelry',
                                                'accessories',
                                                'cropped & shorts',
                                                'flare & boot-cut',
                                                'outerwear',
                                                'blazers',
                                                'tops & shirts',
                                                'leggings',
                                            ],
                            } 



def find_wishlist_cat(wishlist, cat_scheme):
    
    print 'In find_wishlist_cat'
    wishlist_cat = []
    if (cat_scheme == PROD_MODEL_BASED):
        for i in wishlist:
            #print i['category']
            wishlist_cat.append(i['category'])
    return wishlist_cat

def mark_category_gender(store_name):
    brand = Brands.objects.get(name = store_name)
    male_categories = static_male_categories[brand.name]
    female_categories = static_female_categories[brand.name]
    print len(set(male_categories))
    for cat in set(male_categories):
        #print cat
        try:
            existing_item = StoreSpecificItemCategory.objects.filter(brand = brand).get(categoryName = cat)
        except ObjectDoesNotExist:
            item = StoreSpecificItemCategory(brand = brand,
                                             categoryName = cat,
                                             gender = 'Men')
            print "Men Item Creation", smart_unicode(cat)
            item.save()
        else:
            if existing_item.gender == 'Nil':
                existing_item.gender = 'Men'
                existing_item.save()
                print "Category " + cat + " exists, Marking Men"
            elif existing_item.gender == 'Women':
                existing_item.gender = 'Both'
                existing_item.save()
                print "Category " + cat + " exists, marking Both"
            
    for cat in set(female_categories):
        #print cat
        try:
            existing_item = StoreSpecificItemCategory.objects.filter(brand = brand).get(categoryName = cat)
        except ObjectDoesNotExist:
            item = StoreSpecificItemCategory(brand = brand,
                                             categoryName = cat,
                                             gender = 'Women')
            print "Women Item Creation", smart_unicode(item)
            item.save()
        else:
            if existing_item.gender == 'Nil':
                existing_item.gender = 'Women'
                existing_item.save()
                print "Category " + cat + " exists, marking Women"
            elif existing_item.gender == 'Men':
                existing_item.gender = 'Both'
                existing_item.save()
                print "Category " + cat + " exists, marking Both"


def fill_category(store_name):
    brand = Brands.objects.get(name = store_name)
    categories = static_categories[brand.name]
    for cat in categories:
        print cat
        old_item = StoreSpecificItemCategory.objects.filter(brand = brand).filter(categoryName = cat)
        if len(old_item) > 0:
            print "Category " + cat + " already exists, skipping creating new one"
        item = StoreSpecificItemCategory(brand = brand,
                                         categoryName = cat)
        item.save()
        print "Created new entry for category " + cat
        print item

if __name__ == "__main__":
    
    print 'Testing'
    print len(static_categories['Express']), len(static_categories['Abercrombie & Fitch'],)
    