---
- name: Transfer and execute a script.
  hosts: Postprocessing
  remote_user: ubuntu
  sudo: yes
  tasks:
     - name: Creates directory
       file: path=/home/ubuntu/ascripts state=directory

     - name: Transfer the script
       copy: src=/home/ubuntu/Projects_DEFAULT/miami_metro/servermonitoring/supervisord.py dest=/home/ubuntu/ascripts/ mode=0777

     - name: Install Python packages
       pip: name=baker

     - name: Execute the script
       shell: python /home/ubuntu/ascripts/supervisord.py print_local_status
       register: result
       changed_when: result.stdout
     - debug: msg="{{result.stdout}}"
       when: result.stdout
