# encoding: utf-8


"""
Dictionary to collect Influencer viewers age distribution
"""
influencer_age_groups_dict = {
    '0_19': ['abercrombie', 'Abercrombie & Fitch', 'Aeropostale', 'Aldo', 'American Apparel', 'American Eagle',
             'americanapparel', 'americaneagle', 'asos ', 'BCBG', 'Bebe', 'boohoo', 'brandy melville', 'brandymelville',
             'Chicwish', 'Choies', 'chuck taylor', 'chucktaylor', 'For Love & Lemons', 'Forever 21', 'forever21',
             'free people', 'freepeople', 'Gap', 'H&M', 'Joe Fresh', 'Levis', 'Lulus', 'Mavi Jeans',
             'Miss Guided', 'missguided', 'modcloth', 'nasty gal', 'nastygal', 'Old Navy', 'Romwe', 'sheinside',
             'Ted Baker', 'topshop', 'UGG', 'UGGs', 'urban outfitters', 'urbanoutfitters', 'Vans', 'wet seal',
             'wetseal', 'Yoox', 'zara', 'backpack', 'beanie', 'crop top', 'fashion sneaker', 'flip-flops', 'jumper',
             'nail art', 'nailart', 'romper', 'skort', 'snapback hat', 'sneakerporn', 'streetwear', 'benefit cosmetics',
             'biore', 'covergirl', 'e.l.f.', 'essie', 'fake eyelashes', "l'oreal", 'loreal', 'maybelline',
             'nyx cosmetics', 'OPI', 'revlon', 'rimmel', 'sally hansen', 'tarte', 'urban decay', 'wet n wild',
             'study abroad', 'studying abroad', 'music festival', 'camping', 'interning', 'partying', 'bar hopping',
             'barhopping', 'beer pong', 'beerpong', 'keg stand', 'kegstand', 'drinking game', 'fraternity', 'sorority',
             'dorm', 'frat', 'my highschool', 'my high school', 'my classes', 'my professor', ],
    '20_24': ['abercrombie', 'Abercrombie & Fitch', 'Adidas', 'Aeropostale', 'Aldo', 'American Apparel',
              'American Eagle', 'americanapparel', 'americaneagle', 'asos ', 'BCBG', 'Bebe', 'boohoo',
              'brandy melville', 'brandymelville', 'Chicwish', 'Choies', 'chuck taylor', 'chucktaylor', 'Design Lab',
              'For Love & Lemons', 'Forever 21', 'free people', 'freepeople', 'G Star', 'Gap', 'Gstar', 'H&M',
              'Joe Fresh', 'Levis', 'Lululemon', 'lulus', 'Lulus', 'Madewell', 'Mavi Jeans', 'MinkPink', 'Miss Guided',
              'missguided', 'modcloth', 'nasty gal', 'nastygal', 'Old Navy', 'oldnavy', 'Ray-Ban', 'rayban', 'Romwe',
              'sheinside', 'Ted Baker', 'top shop', 'topshop', 'UGG', 'UGGs', 'urban outfitters', 'Vans', 'wet seal',
              'wetseal', 'Yoox', 'zara', 'backpack', 'boyfriend tee', 'crop top', 'fashion sneaker', 'jumper',
              'mom jeans', 'moto jacket', 'nail art', 'nailart', 'pleather', 'romper', 'sneakerporn', 'streetwear',
              'benefit cosmetics', 'cat eyes', 'clarisonic', 'essie', 'fake eyelashes', 'josie maran', 'lorac',
              'maybelline', 'smashbox', 'tarte', 'too faced', 'toofaced', 'urban decay', 'backpacking', 'camping',
              'music festival', 'Vegas', 'drinking game', 'barhopping', 'bar hopping', 'ikea', 'clubbing',
              'apartment', ],
    '25_29': ['Adidas', 'Aldo', 'All Saints', 'allsaints', 'American Apparel', 'american apparel', 'anthropologie',
              'Aritzia', 'asos ', 'bauble bar', 'baublebar', 'BCBG', 'birchbox', 'Blank NYC', 'blanknyc',
              'chuck taylor', 'club monaco', 'Converse', 'Design Lab', 'Diane von Furstenberg', 'DVF', 'free people',
              'freepeople', 'H&M', 'J Brand', 'j crew', 'j. crew', 'jcrew', 'Joe Fresh', 'Levis', 'lilly pulitzer',
              'lillypulitzer', 'Links of London', 'Lululemon', 'Lulus', 'madewell', 'Marc Jacobs', 'MinkPink',
              'modcloth', 'Old Navy', 'Ray-Ban', 'rayban', 'rebecca minkoff', 'sheinside', 'Sole Society', 'stitchfix',
              'the reformation', 'tieks', 'Tiffany & Co.', 'top shop', 'topshop', 'uniqlo', 'urban outfitters', 'Vans',
              'zara', 'backpack', 'blanket scarf', 'boyfriend tee', 'crop top', 'fashion sneaker', 'lace dress',
              'moto jacket', 'romper', 'slip dress', 'sneakerporn', 'streetwear', 'bare minerals', 'benefit cosmetics',
              'cat eyes', 'charlotte tilbury', 'clarisonic', 'fake eyelashes', 'glamglow', 'josie maran',
              'kate somerville', 'smashbox', 'tarte', 'too faced', 'toofaced', 'urban decay', 'honeymoon',
              'all-inclusive', 'Vegas', 'bride', 'groom', 'bridesmaid', 'maid of honor', 'groomsmen', 'wedding',
              'rehearsal dinner', 'wedding favor', 'ceremony', 'ikea', 'West Elm', 'new born', 'new baby', 'toddler',
              'baby sling', 'baby carrier', 'carseat', 'car seat', 'infant', 'crib', 'pregnancy', ],
    '30_34': ['All Saints', 'allsaints', 'anthropologie', 'asos', 'Banana Republic', 'bananarepublic', 'barneys',
              'bauble bar', 'baublebar', 'birchbox', 'Blank NYC', 'blanknyc', 'Calvin Klein', 'CalvinKlein',
              'Clover Canyon', 'Club Monaco', 'david yurman ', 'davidyurman ', 'Diane von Furstenberg', 'dsw', 'DVF',
              'farfetch', 'French Connection', 'j crew', 'j. crew', 'jcrew', 'kate spade', 'katespade', 'kenneth cole',
              'Links of London', 'Lululemon', 'madewell', 'michaelkors', 'Moschino', 'net a porter', 'net-a-porter',
              'netaporter', 'Nine West', 'nordstrom', 'north face', 'Rag & Bone', 'ralph lauren', 'ralphlauren',
              'Ray-Ban', 'rayban', 'Rebecca Minkoff ', 'revolve clothing', 'revolveclothing', 'stella & dot',
              'stellaanddot', 'stewart weitzman', 'stitchfix', 'the loft', 'the reformation', 'therealreal', 'tieks',
              'Tiffany & Co.', 'tory burch', 'toryburch', 'valentino', 'zara', 'blazer', 'blouse', 'button-down',
              'pearls', 'pencil skirt', 'Algenist', 'bare minerals', 'charlotte tilbury', 'dior', 'drunk elephant',
              'josie maran', 'kate somerville', 'ole henriksen', 'Peter Thomas Roth', 'shiseido', 'sunscreen',
              'too faced', 'toofaced', 'cruise', 'all-inclusive', 'my home', 'redecorating', 'renovating', 'renovation',
              'gardening', 'West Elm', 'westelm', 'dinner party', 'decor', 'new born', 'new baby', 'toddler',
              'baby sling', 'baby carrier', 'carseat', 'car seat', 'infant', 'crib', 'pregnancy', 'potty training', ],
    '35_39': ['Acne Studios', 'ann taylor', 'anne klein', 'anntaylor', 'anthropologie', 'bananarepublic',
              'Banana Republic', 'barneys', 'barneys', "Bloomingdale's", 'Bloomingdales', 'boden', 'Burberry',
              'Christian Dior', 'Clover Canyon', 'Club Monaco', 'Coach', 'David Yurman', 'Diane von Furstenberg', 'DVF',
              'Eileen Fisher', 'French Connection', 'gigi new york', 'j crew', 'j. crew', 'jcpenney', 'jcrew',
              'jessica simpson', 'kate spade', 'katespade', 'kenneth cole', 'lilly pulitzer', 'lillypulitzer',
              'Lord & Taylor', 'Lucky Brand', 'Max Mara', 'michael kors', 'michaelkors', 'new york and co.',
              'nine west', 'north face', 'ralph lauren', 'ralphlauren', 'Rebecca Minkoff ', 'the limited', 'the loft',
              'therealreal', 'tieks', 'Tiffany & Co.', 'tory burch', 'toryburch', 'White House Black Market', 'zara',
              'blazer', 'blouse', 'button-down', 'cowl neck', 'diamond earrings', 'nightgown', 'pea coat', 'pearls',
              'pencil skirt', 'Algenist', 'anti-aging', 'bare minerals', 'clinique', 'collagen', 'dennis gross', 'dior',
              'drunk elephant', 'estee lauder', 'fine lines', 'kate somerville', 'lancome', 'my home', 'ole henriksen',
              'Peter Thomas Roth', 'shiseido', 'tom ford', 'cruise', 'groupon', 'my home', 'redecorating', 'renovating',
              'renovation', 'gardening', 'West Elm', 'westelm', 'dinner party', 'decor', 'back to school',
              'afterschool', 'after-school', 'soccer practice', 'her teacher', 'his teacher', 'homework',
              'disney world', 'family vacation', 'family vaca', 'family vacay', 'family holiday', ],
    '40': ['aerosoles', 'ann taylor', 'anne klein', 'anntaylor', 'banana republic', 'bananarepublic', 'barneys',
           "Bloomingdale's", 'Bloomingdales', 'boden', 'Burberry', 'chicos', 'christopher and banks', 'clarkes',
           'Club Monaco', 'Coach', 'coldwater creek', 'David Yurman', 'Diane von Furstenberg', 'donna karan',
           'dress barn', 'dsw', 'dvf', 'ecco', 'eddie bauer', 'Eileen Fisher', 'j crew', 'j. crew', 'j. jill', 'j.jill',
           'jcpenney', 'jcrew', 'jessica simpson', 'kate spade', 'katespade', 'kenneth cole', 'kohls', 'landsend',
           'lilly pulitzer', 'Lord & Taylor', 'Lucky Brand', 'michael kors', 'michaelkors', 'new york and co.',
           'nine west', 'ralph lauren', 'ralphlauren', 'steinmart', 'talbots', 'Tory Burch', 'toryburch',
           'White House Black Market', 'woolrich', 'blouse', 'button-down', 'cowl neck', 'diamond earrings', 'loafers',
           'nightgown', 'pearls', 'pencil skirt', 'poncho', 'tennis bracelet', 'windbreaker', 'Algenist', 'anti-aging',
           'bare minerals', 'clinique', 'collagen', 'dennis gross', 'dior', 'drunk elephant', 'estee lauder',
           'fine lines', 'lancome', 'my home', 'ole henriksen', 'Peter Thomas Roth', 'shiseido', 'tom ford', 'cruise',
           'bus tour', 'granite counter', 'bathroom tile', 'home improvement', 'my home', 'redecorating', 'renovating',
           'renovation', 'gardening', 'West Elm', 'westelm', 'dinner party', 'decor', 'my grandchild', 'my grandkids'],
}



