import json


STRIPE_PLANS_JSON = '''
[{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_24000", 
    "created": 1458180900, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_24000", 
    "currency": "usd", 
    "amount": 2400000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_MONTHLY_1500", 
    "created": 1457453289, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "STRIPE_MONTHLY_1500", 
    "currency": "usd", 
    "amount": 150000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_HALF_YEARLY_5000", 
    "created": 1457059051, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "THESHELF_HALF_YEARLY_5000", 
    "currency": "usd", 
    "amount": 250000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_QUARTERLY_PLAN_10800", 
    "created": 1456340637, 
    "interval": "month", 
    "interval_count": 3, 
    "id": "THESHELF_QUARTERLY_PLAN_10800", 
    "currency": "usd", 
    "amount": 270000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_MONTHLY_3500", 
    "created": 1454983132, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "THESHELF_MONTHLY_3500", 
    "currency": "usd", 
    "amount": 350000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_18000", 
    "created": 1454884472, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_18000", 
    "currency": "usd", 
    "amount": 1800000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": "THESHELF YEARLY PLAN", 
    "statement_description": "THESHELF YEARLY PLAN", 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_HALF_YEARLY_5400", 
    "created": 1453836767, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "STRIPE_HALF_YEARLY_5400", 
    "currency": "usd", 
    "amount": 540000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_MONTHLY_775", 
    "created": 1452891949, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "STRIPE_MONTHLY_775", 
    "currency": "usd", 
    "amount": 77500, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_MONTHLY_900", 
    "created": 1452890328, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "STRIPE_MONTHLY_900", 
    "currency": "usd", 
    "amount": 90000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_937", 
    "created": 1452033191, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_937", 
    "currency": "usd", 
    "amount": 93700, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_SEMI_ANNUAL_5000", 
    "created": 1451602854, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "THESHELF_SEMI_ANNUAL_5000", 
    "currency": "usd", 
    "amount": 500000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_1300", 
    "created": 1450904076, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_1300", 
    "currency": "usd", 
    "amount": 130000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_100", 
    "created": 1450819105, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_100", 
    "currency": "usd", 
    "amount": 10000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_637", 
    "created": 1450815912, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_637", 
    "currency": "usd", 
    "amount": 63700, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_525", 
    "created": 1450815886, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_525", 
    "currency": "usd", 
    "amount": 52500, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_475", 
    "created": 1450815855, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_475", 
    "currency": "usd", 
    "amount": 47500, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "BoneBroth_Activation", 
    "created": 1445262688, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "BoneBroth_Activation", 
    "currency": "usd", 
    "amount": 170000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "VII_BEAUTY_SPECIAL", 
    "created": 1444960152, 
    "interval": "month", 
    "interval_count": 12, 
    "id": "VII_BEAUTY_SPECIAL", 
    "currency": "usd", 
    "amount": 110000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_6500_SEMIANNUAL", 
    "created": 1444144361, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "THESHELF_6500_SEMIANNUAL", 
    "currency": "usd", 
    "amount": 650000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_CORONEL_SMITH_SPECIAL", 
    "created": 1438289018, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "THESHELF_CORONEL_SMITH_SPECIAL", 
    "currency": "usd", 
    "amount": 1000000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_YEARLY_1000", 
    "created": 1436455793, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_YEARLY_1000", 
    "currency": "usd", 
    "amount": 100000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_CARATLONDON_SPECIAL_PRICING", 
    "created": 1434979593, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "THESHELF_CARATLONDON_SPECIAL_PRICING", 
    "currency": "usd", 
    "amount": 180000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_VIIVIIVII_SPECIAL_MONTHLY", 
    "created": 1434654505, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "THESHELF_VIIVIIVII_SPECIAL_MONTHLY", 
    "currency": "usd", 
    "amount": 83300, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_INFLUENCER_DATA_PLAN_4500", 
    "created": 1434464365, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "THESHELF_INFLUENCER_DATA_PLAN_4500", 
    "currency": "usd", 
    "amount": 450000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_HALF_YEARLY_SPECIAL_WINNIEANDKATE", 
    "created": 1433722239, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "THESHELF_HALF_YEARLY_SPECIAL_WINNIEANDKATE", 
    "currency": "usd", 
    "amount": 150000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_JEWELRYSNUG_SPECIAL_PLAN", 
    "created": 1432676252, 
    "interval": "month", 
    "interval_count": 4, 
    "id": "THESHELF_JEWELRYSNUG_SPECIAL_PLAN", 
    "currency": "usd", 
    "amount": 200000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "THESHELF_DEWPUFF_STARTUP_PLAN", 
    "created": 1432658607, 
    "interval": "month", 
    "interval_count": 4, 
    "id": "THESHELF_DEWPUFF_STARTUP_PLAN", 
    "currency": "usd", 
    "amount": 100000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_11200", 
    "created": 1431348614, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_11200", 
    "currency": "usd", 
    "amount": 1120000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "MULTIPLE_MONTH_6_SMALL_BRANDS_500", 
    "created": 1424713161, 
    "interval": "month", 
    "interval_count": 6, 
    "id": "MULTIPLE_MONTH_6_SMALL_BRANDS_500", 
    "currency": "usd", 
    "amount": 300000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_MONTHLY", 
    "created": 1424313558, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_MONTHLY", 
    "currency": "usd", 
    "amount": 83333, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_36000", 
    "created": 1423776348, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_36000", 
    "currency": "usd", 
    "amount": 3600000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_10000", 
    "created": 1423519780, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_10000", 
    "currency": "usd", 
    "amount": 1000000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_5000", 
    "created": 1423519626, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_5000", 
    "currency": "usd", 
    "amount": 500000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "MULTIPLE_MONTH_3_SMALL_BRANDS_500", 
    "created": 1423257049, 
    "interval": "month", 
    "interval_count": 3, 
    "id": "MULTIPLE_MONTH_3_SMALL_BRANDS_500", 
    "currency": "usd", 
    "amount": 150000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "INTRO_PLAN", 
    "created": 1421894812, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "INTRO_PLAN", 
    "currency": "usd", 
    "amount": 5000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": "THESHELF.COM", 
    "statement_description": "THESHELF.COM", 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "DOWNLOAD_CUSTOM_100_MILAN_100_US", 
    "created": 1421251127, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "DOWNLOAD_CUSTOM_100_MILAN_100_US", 
    "currency": "usd", 
    "amount": 130000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": "TheSHElf.com", 
    "statement_description": "TheSHElf.com", 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_10800", 
    "created": 1418684148, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_10800", 
    "currency": "usd", 
    "amount": 1080000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_12000", 
    "created": 1418684072, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_12000", 
    "currency": "usd", 
    "amount": 1200000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_9600", 
    "created": 1418684050, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_9600", 
    "currency": "usd", 
    "amount": 960000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_8400", 
    "created": 1418684017, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_8400", 
    "currency": "usd", 
    "amount": 840000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_7200", 
    "created": 1418684001, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_7200", 
    "currency": "usd", 
    "amount": 720000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_6000", 
    "created": 1418683980, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_6000", 
    "currency": "usd", 
    "amount": 600000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_4800", 
    "created": 1418683967, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_4800", 
    "currency": "usd", 
    "amount": 480000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_3600", 
    "created": 1418683950, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_3600", 
    "currency": "usd", 
    "amount": 360000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_2400", 
    "created": 1418683932, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_2400", 
    "currency": "usd", 
    "amount": 240000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_15000", 
    "created": 1418683906, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_15000", 
    "currency": "usd", 
    "amount": 1500000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_20000", 
    "created": 1418683854, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_20000", 
    "currency": "usd", 
    "amount": 2000000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_25000", 
    "created": 1418683830, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_25000", 
    "currency": "usd", 
    "amount": 2500000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_30000", 
    "created": 1418683816, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_30000", 
    "currency": "usd", 
    "amount": 3000000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "STRIPE_PLAN_AGENCY_YEARLY_12000", 
    "created": 1417640115, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "STRIPE_PLAN_AGENCY_YEARLY_1000", 
    "currency": "usd", 
    "amount": 1200000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PR_YEARLY_1", 
    "created": 1417546547, 
    "interval": "year", 
    "interval_count": 1, 
    "id": "PR_YEARLY_1", 
    "currency": "usd", 
    "amount": 1200000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_800", 
    "created": 1416247257, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_800", 
    "currency": "usd", 
    "amount": 80000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_3750", 
    "created": 1407854506, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_3750", 
    "currency": "usd", 
    "amount": 375000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_500", 
    "created": 1407519676, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_500", 
    "currency": "usd", 
    "amount": 50000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_400", 
    "created": 1407519664, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_400", 
    "currency": "usd", 
    "amount": 40000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_300", 
    "created": 1407519652, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_300", 
    "currency": "usd", 
    "amount": 30000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "ENTERPRISE_PLAN_200", 
    "created": 1406915899, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "ENTERPRISE_PLAN_200", 
    "currency": "usd", 
    "amount": 20000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_1000", 
    "created": 1406257512, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_1000", 
    "currency": "usd", 
    "amount": 100000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_900", 
    "created": 1406257502, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_900", 
    "currency": "usd", 
    "amount": 90000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_800", 
    "created": 1406257491, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_800", 
    "currency": "usd", 
    "amount": 80000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_700", 
    "created": 1406257478, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_700", 
    "currency": "usd", 
    "amount": 70000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_600", 
    "created": 1406257466, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_600", 
    "currency": "usd", 
    "amount": 60000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_500", 
    "created": 1406257454, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_500", 
    "currency": "usd", 
    "amount": 50000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_400", 
    "created": 1406257443, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_400", 
    "currency": "usd", 
    "amount": 40000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "PLAN_100", 
    "created": 1406257408, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "PLAN_100", 
    "currency": "usd", 
    "amount": 10000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "Agency", 
    "created": 1404496798, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "Agency", 
    "currency": "usd", 
    "amount": 12500, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "Per_seat", 
    "created": 1404130957, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "Per_seat", 
    "currency": "usd", 
    "amount": 10000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "Enterprise", 
    "created": 1403098564, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "Enterprise", 
    "currency": "usd", 
    "amount": 10000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": null, 
    "statement_description": null, 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "Basic", 
    "created": 1399517538, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "Basic", 
    "currency": "usd", 
    "amount": 2900, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": "Basic Plan", 
    "statement_description": "Basic Plan", 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "Cheap", 
    "created": 1399517506, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "Cheap", 
    "currency": "usd", 
    "amount": 900, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": "Cheap Plan", 
    "statement_description": "Cheap Plan", 
    "metadata": {}
}, 
{
    "object": "plan", 
    "name": "Startup", 
    "created": 1397569098, 
    "interval": "month", 
    "interval_count": 1, 
    "id": "Startup", 
    "currency": "usd", 
    "amount": 10000, 
    "trial_period_days": null, 
    "livemode": true, 
    "statement_descriptor": "Startup Plan", 
    "statement_description": "Startup Plan", 
    "metadata": {}
}]
'''

STRIPE_PLANS = json.loads(STRIPE_PLANS_JSON)